routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/home', 'HomeController@index')->name('home');
Route::post('/backlogitemsave', 'HomeController@save')->name('backlogItemSave'); //Les 2
Route::delete('/removebli', 'homeController@removebli');

Route::get('/planning','PlanningController@index')->name('planning');
Route::post('/planning','PlanningController@store')->name('planningstore');
Route::delete('/deleteplanning','PlanningController@deleteplanning');

Route::get('/retrospective','RetrospectiveController@index')->name('retrospective');
Route::post('/retrosave', 'RetrospectiveController@save')->name('retroSave');

Auth::routes();
Route::resource('project', 'ProjectController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    public function backlog_items()
    {
        return $this->hasMany(BacklogItem::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->using(ProjectUser::class);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectCreateRequest;
use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $projects = Project::paginate(6);
        return view('projects.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
//        return view('project.create', compact('projects'));
        return view('project.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        return request()->all();
//        return request('title');

        $project = new Project;

        $project->title = $request->title;
        $project->description = $request->description;
        $project->deadline= $request->deadline;
        $project->save();

        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
    }

    public function save(ProjectCreateRequest $request)
    {
        $data = $request->validated();
        $projects = new Project();
        $projects->title = $data['title'];
        $projects->description = $data['description'];
        $projects->deadline = $data['deadline'];

        $projects->save();

        return redirect()->back();
    }
}

resources/views/projects/create.blade.php
<?php

resources/views/projects/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Timothy
 * Date: 2-12-2019
 * Time: 11:41
 */

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container text-center"><h4>Mijn projecten</h4></div>
    <div class="container">
        <div class="row justify-content-center">
            @foreach($projects as $project)
                <div class="col-4">
                    <div class="card">
                        <div class="card-header">
                            {{ $project->title }}
                        </div>
                        <div class="card-body">
                            Omschrijving project :{{ $project->description }}
                            <br>
                            Deadline :{{ $project->deadline }}
                        </div>
                    </div>
                    <br>
                </div>
            @endforeach
        </div>
        <br>
        <div class="container">
            <div class="row justify-content-center">
                <div id="paginationEvents" style="text-align: center">
                    <div id="bar">
                        {{ $projects->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{--create project--}}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-5">
                <div class="card">
                    <form action="{{ route('project.store') }}" method="post">
                        @csrf
                        <div class="card-header">
                            <a>Naam project </a><input type="text" name="title" placeholder="Scrum" required><br><br>
                            <a>Beschrijving </a><textarea name="description" placeholder="beschrijving project"></textarea>
                            {{--<input type="text" name="activity" required>--}}
                        </div>
                        <div class="card-body">
                            Deadline: <input type="date" name="deadline" placeholder="2020-01-10" required><br><br>
                            <div class="text-center">
                                <input type="submit" value="Maak nieuw project">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{--end create project--}}
@endsection

resources/views/projects/show.blade.php
<?php